#!/bin/bash
#
# cloud-scheduler-stats		Start up the cloud-scheduler-stats daemon
#
# chkconfig: 2345 55 25
# description: cloud-scheduler-stats is a deamon for monitoring\ 
#              cloud scheduler
#
# processname: cloud-scheduler-stats
# config: /etc/cloudscheduler/cloud_stats.conf
# pidfile: /var/run/cloud-scheduler-stats.pid

### BEGIN INIT INFO
# Provides: cloud-scheduler-stats
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the OpenSSH server daemon
# Description:       SSH is a protocol for secure remote shell access.
#		     This service starts up the OpenSSH server daemon.
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions


RETVAL=0
prog="cloud-scheduler-stats"
lockfile=/var/lock/subsys/$prog

# Some functions to make the below more readable
CSSTATS=/usr/bin/cloud-scheduler-stats
PID_FILE=/var/run/cloud-scheduler-stats.pid

runlevel=$(set -- $(runlevel); eval "echo \$$#" )




do_restart_sanity_check()
{
	$CSSTATS -t
	RETVAL=$?
	if [ $RETVAL -ne  0 ]; then
		failure $"Configuration file or keys are invalid"
		echo
	fi
}

start()
{
	[ -x $CSSTATS ] || exit 5
	[ -f /etc/cloudscheduler/cloud_stats.conf ] || exit 6

	echo -n $"Starting $prog: "
        #daemon --check --pidfile=$PID_FILE $CSSTATS $OPTIONS &
        /sbin/runuser -l -s /bin/bash root -c $CSSTATS $OPTIONS & 
	RETVAL=$?

	if [ $RETVAL -eq 0 ]; then
		echo $! > $PID_FILE
		touch $lockfile
		success
	else
		failure 
	fi
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE $CSSTATS
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	echo
}

reload()
{
	echo -n $"Reloading $prog: "
	killproc -p $PID_FILE $CSSTATS -HUP
	RETVAL=$?
	echo
}

restart() {
	stop
	start
}

force_reload() {
	restart
}

rh_status() {
	status -p $PID_FILE cloud-scheduler-stats
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		start
		;;
	stop)
		if ! rh_status_q; then
			rm -f $lockfile
			exit 0
		fi
		stop
		;;
	restart)
		restart
		;;
	reload)
		rh_status_q || exit 7
		reload
		;;
	force-reload)
		force_reload
		;;
	condrestart|try-restart)
		rh_status_q || exit 0
		if [ -f $lockfile ] ; then
			do_restart_sanity_check
			if [ $RETVAL -eq 0 ] ; then
				stop
				# avoid race
				sleep 3
				start
			else
				RETVAL=6
			fi
		fi
		;;
	status)
		rh_status
		RETVAL=$?
		if [ $RETVAL -eq 3 -a -f $lockfile ] ; then
			RETVAL=2
		fi
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
		RETVAL=2
esac
exit $RETVAL
